######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 6 19:54:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += signal1.cpp
