######################################################################
# Automatically generated by qmake (3.1) Sat Oct 6 16:28:12 2018
######################################################################

TEMPLATE = app
TARGET = waitconditions
INCLUDEPATH += .

# Input
SOURCES += waitconditions.cpp
