######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 27 12:27:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
