######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 27 16:45:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
