######################################################################
# Automatically generated by qmake (3.0) Thu Aug 28 00:06:49 2014
######################################################################

TEMPLATE = app
TARGET = filedialog
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += resource.qrc

QT += widgets
CONFIG += c++11
