######################################################################
# Automatically generated by qmake (3.0) Tue Aug 26 23:13:45 2014
######################################################################

TEMPLATE = app
TARGET = qdialog
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += res.qrc

QT += widgets
