######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 5 20:30:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += byteConvertDialog.ui
SOURCES += main.cpp
