######################################################################
# Automatically generated by qmake (3.0) Sat Dec 10 13:08:40 2016
######################################################################

TEMPLATE = app
TARGET = events
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += eventLabel.cpp
