######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 31 21:29:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += byteConverter.h \
    byteconvertdialog.h
SOURCES += byteConverter.cpp \
    main.cpp \
    byteconvertdialog.cpp
