######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 8 16:49:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += combobox.h
SOURCES += combobox.cpp main.cpp
