######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 6 13:51:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
