######################################################################
# Automatically generated by qmake (3.0) Sun Aug 24 21:46:08 2014
######################################################################

TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
