######################################################################
# Automatically generated by qmake (3.0) Sat Aug 30 09:53:11 2014
######################################################################

TEMPLATE = app
TARGET = gradient
INCLUDEPATH += .

# Input
HEADERS += painter.h
SOURCES += main.cpp painter.cpp

QT += widgets
