######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 7 09:16:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h
