######################################################################
# Automatically generated by qmake (3.0) Thu Aug 28 22:12:50 2014
######################################################################

TEMPLATE = app
TARGET = eventsum
INCLUDEPATH += .

# Input
HEADERS += label.h
SOURCES += main.cpp

QT += widgets
