######################################################################
# Automatically generated by qmake (3.0) Sat Aug 30 10:42:32 2014
######################################################################

TEMPLATE = app
TARGET = translate
INCLUDEPATH += .

# Input
HEADERS += painter.h
SOURCES += main.cpp painter.cpp

QT += widgets
