######################################################################
# Automatically generated by qmake (3.1) Sat Oct 6 12:38:50 2018
######################################################################

TEMPLATE = app
TARGET = semaphores
INCLUDEPATH += .

# Input
SOURCES += semaphores.cpp
