######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 19 23:48:57 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += newspaper.h reader.h
SOURCES += newspaper.cpp
