######################################################################
# Automatically generated by qmake (3.0) ?? 6? 14 15:12:08 2014
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
