######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 7 20:04:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
