######################################################################
# Automatically generated by qmake (3.0) Tue Aug 26 22:07:52 2014
######################################################################

TEMPLATE = app
TARGET = mainwindow
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += mainwindow.qrc

QT += widgets
