######################################################################
# Automatically generated by qmake (2.01a) Sun May 11 12:37:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gobang.h window.h
SOURCES += gobang.cpp main.cpp window.cpp
