######################################################################
# Automatically generated by qmake (3.0) Sat Aug 30 11:27:28 2014
######################################################################

TEMPLATE = app
TARGET = qfile
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets
