######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 4 21:50:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
