######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 14 10:50:47 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += buttons.h
SOURCES += buttons.cpp main.cpp
QT += widgets
