######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 4 21:31:00 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h window.h Wuziqi.h
SOURCES += dialog.cpp main.cpp window.cpp Wuziqi.cpp
