######################################################################
# Automatically generated by qmake (3.0) Sat Aug 30 10:54:14 2014
######################################################################

TEMPLATE = app
TARGET = modelview
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets
