######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 7 15:31:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += layout1.cpp
