######################################################################
# Automatically generated by qmake (3.0) Tue Aug 19 22:52:29 2014
######################################################################

TEMPLATE = app
TARGET = sig5
INCLUDEPATH += .

# Input
HEADERS += newspaper.h reader.h
SOURCES += newspaper.cpp

QT += widgets
