######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 8 09:41:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lineedit.h
SOURCES += linedit.cpp main.cpp
