######################################################################
# Automatically generated by qmake (2.01a) Tue May 27 17:24:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gobang.h window.h
SOURCES += gobang.cpp main.cpp window.cpp
