######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 6 19:06:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += signal.cpp
