######################################################################
# Automatically generated by qmake (3.0) ?? 6? 14 11:10:06 2014
######################################################################

TEMPLATE = app
TARGET = buttonWindow
INCLUDEPATH += .

# Input
HEADERS += button.h
SOURCES += button.cpp
QT += widgets
