######################################################################
# Automatically generated by qmake (3.1) Sat Oct 6 10:12:55 2018
######################################################################

TEMPLATE = app
TARGET = threads
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += thread.h threaddialog.h
SOURCES += main.cpp thread.cpp threaddialog.cpp
