######################################################################
# Automatically generated by qmake (3.0) ?? 6? 16 10:55:49 2014
######################################################################

TEMPLATE = app
TARGET = signal
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
