######################################################################
# Automatically generated by qmake (3.0) Sat Aug 30 00:46:47 2014
######################################################################

TEMPLATE = app
TARGET = antialiasing
INCLUDEPATH += .

# Input
HEADERS += painter.h
SOURCES += main.cpp painter.cpp

QT += widgets
