######################################################################
# Automatically generated by qmake (3.1) Tue Oct 23 22:15:20 2018
######################################################################

TEMPLATE = app
TARGET = ftpget
INCLUDEPATH += .
QT += network

# Input
HEADERS += ftpget.h
SOURCES += ftpget.cpp main.cpp
LIBS += -lQt5Ftp
