######################################################################
# Automatically generated by qmake (3.0) Thu Aug 28 21:03:09 2014
######################################################################

TEMPLATE = app
TARGET = eventfilter
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp

QT += widgets
