######################################################################
# Automatically generated by qmake (3.1) Sun Oct 7 10:27:44 2018
######################################################################

TEMPLATE = app
TARGET = imagepro
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += imagewindow.h transactionthread.h
FORMS += resizedialog.ui
SOURCES += imagewindow.cpp main.cpp transactionthread.cpp
