######################################################################
# Automatically generated by qmake (3.0) Thu Aug 28 23:36:02 2014
######################################################################

TEMPLATE = app
TARGET = painter
INCLUDEPATH += .

# Input
HEADERS += painter.h
SOURCES += main.cpp painter.cpp

QT += widgets
