######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 12 22:56:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.hpp treewidgetitem.hpp
SOURCES += main.cpp mainwindow.cpp qrc_aqp.cpp
RESOURCES += playmusic.qrc
