######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 5 11:11:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
