######################################################################
# Automatically generated by qmake (3.0) Tue Aug 19 21:01:36 2014
######################################################################

TEMPLATE = app
TARGET = signal2
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
QMAKE_CXXFLAGS += -std=c++0x
