######################################################################
# Automatically generated by qmake (3.0) Wed Aug 27 23:40:36 2014
######################################################################

TEMPLATE = app
TARGET = eventignore
INCLUDEPATH += .

# Input
HEADERS += custombutton.h
SOURCES += custombutton.cpp main.cpp
