######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 31 22:26:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += converter.h
SOURCES += converterDialog.cpp main.cpp
