######################################################################
# Automatically generated by qmake (3.0) Sat Aug 30 15:20:20 2014
######################################################################

TEMPLATE = app
TARGET = qdatastream
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += widgets
