######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 6 17:03:52 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ByteConvertDialog.h
FORMS += byteConvertDialog.ui
SOURCES += ByteConvertDiaog.cpp main.cpp
