######################################################################
# Automatically generated by qmake (3.1) Tue Oct 23 22:14:55 2018
######################################################################

TEMPLATE = app
TARGET = spider
INCLUDEPATH += .
QT += network

# Input
HEADERS += spider.h
SOURCES += main.cpp spider.cpp
LIBS += -lQt5Ftp
