######################################################################
# Automatically generated by qmake (3.0) Fri Aug 29 22:43:02 2014
######################################################################

TEMPLATE = app
TARGET = painterstyle
INCLUDEPATH += .

# Input
HEADERS += painter.h
SOURCES += main.cpp painter.cpp

QT += widgets
