######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 7 22:16:38 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += layout.h
SOURCES += layout.cpp
