######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 6 17:38:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
