######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 6 11:37:28 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += byteconverdialog.h
FORMS += byteConvertDialog.ui
SOURCES += byteconvertdialog.cpp main.cpp
